# Docker compose configuration for backend express node.js here


services:
  backend:
    container_name: server
    build:
      context: ./backend/
      target: dev
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app/backend
      - backend_node_modules:/app/backend/node_modules

volumes:
  backend_node_modules:
