# Docker compose configuration for backend express node.js here


services:
  backend:
    container_name: TackleIt-Backend
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app/backend
      - backend_node_modules:/app/backend/node_modules
      - staticfiles:/app/backend/static
      - mediafiles:/app/backend/mediafiles

volumes:
  backend_node_modules:
  staticfiles:
  mediafiles:
